### ISSUE TITLE
[BUG] DNS records missing for docs.phantasmlabs.com

### ISSUE THREAD

**Issue by knksmith57** [phantasmlabs/phantasm#9]
### Bug Description

The linked documentation site, https://docs.phantasmlabs.com/, is unreachable due to missing DNS records:

```
❯ dig @1.1.1.1 docs.phantasmlabs.com 

; <<>> DiG 9.10.6 <<>> @1.1.1.1 docs.phantasmlabs.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 43358
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;docs.phantasmlabs.com.		IN	A

;; AUTHORITY SECTION:
phantasmlabs.com.	900	IN	SOA	ns-1505.awsdns-60.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 23 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Thu Oct 31 17:43:40 CDT 2024
;; MSG SIZE  rcvd: 132
```

### Steps to Reproduce

Navigate to https://docs.phantasmlabs.com

**Comment by edwinkys** [comment]
Thank you for reporting!

Both the website and the documentation website is currently under development. I haven't got a chance to complete it since I was preparing for the launch. I will try my best to complete it as soon as possible to fix the issue.
